# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pklshop',
                'doc_host': 'https://NolanSmyth.github.io',
                'git_url': 'https://github.com/NolanSmyth/pklshop',
                'lib_path': 'pklshop'},
  'syms': {'pklshop.core': {'pklshop.core.foo': ('core.html#foo', 'pklshop/core.py')}}}
