# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pklshop',
                'doc_host': 'https://NolanSmyth.github.io',
                'git_url': 'https://github.com/NolanSmyth/pklshop',
                'lib_path': 'pklshop'},
  'syms': { 'pklshop.connect': { 'pklshop.connect.DbConnection': ('connect.html#dbconnection', 'pklshop/connect.py'),
                                 'pklshop.connect.DbConnection.__init__': ('connect.html#dbconnection.__init__', 'pklshop/connect.py'),
                                 'pklshop.connect.DbConnection.__str__': ('connect.html#dbconnection.__str__', 'pklshop/connect.py'),
                                 'pklshop.connect.DbConnection._close': ('connect.html#dbconnection._close', 'pklshop/connect.py'),
                                 'pklshop.connect.DbConnection._connect': ('connect.html#dbconnection._connect', 'pklshop/connect.py'),
                                 'pklshop.connect.DbConnection.pull_data': ('connect.html#dbconnection.pull_data', 'pklshop/connect.py'),
                                 'pklshop.connect.config': ('connect.html#config', 'pklshop/connect.py')},
            'pklshop.data': {'pklshop.data.get_tab_as_df': ('data.html#get_tab_as_df', 'pklshop/data.py')},
            'pklshop.stats': {'pklshop.stats.get_tab_as_df': ('stats.html#get_tab_as_df', 'pklshop/stats.py')}}}
