# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_connect.ipynb.

# %% auto 0
__all__ = ['config']

# %% ../nbs/00_connect.ipynb 3
from configparser import ConfigParser

def config(filename="../database.ini", section="postgresql"):
    """Reads the database.ini file and returns the connection parameters as a dictionary.
    Assumes the ini file is in the parent directory"""
    # create a parser
    parser = ConfigParser()
    # read config file
    parser.read(filename)

    # get section, default to postgresql
    db = {}
    if parser.has_section(section):
        params = parser.items(section)
        for param in params:
            db[param[0]] = param[1]
    else:
        raise Exception(
            "Section {0} not found in the {1} file".format(section, filename)
        )

    return db
