# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_data.ipynb.

# %% auto 0
__all__ = ['table_names', 'table_dict', 'rally', 'players', 'game', 'team', 'match', 'shot', 'tournament', 'load_dfs_from_csv']

# %% ../nbs/01_data.ipynb 3
from .connect import *
import pkgutil
from io import BytesIO
import pandas as pd

# %% ../nbs/01_data.ipynb 4
table_names = ["tournament", "match", "game", "rally", "shot_type_ref", "shot", "player", "team",]

# %% ../nbs/01_data.ipynb 6
#This is a function to get the dataframes from the csv files
def load_dfs_from_csv():
    "Returns a dictionary of dataframes from the table csv files"
    table_dict = {}
    for table_name in table_names:
        table_dat = pkgutil.get_data('pklshop', f"datasets/{table_name}.csv")
        df = pd.read_csv(BytesIO(table_dat))
        table_dict[table_name] = df
    return table_dict

table_dict = load_dfs_from_csv()

rally = table_dict["rally"]
players = table_dict["player"]
game = table_dict["game"]
team = table_dict["team"]
match = table_dict["match"]
shot = table_dict["shot"]
tournament = table_dict["tournament"]
