# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_match.ipynb.

# %% auto 0
__all__ = ['Match']

# %% ../nbs/05_match.ipynb 3
from .data import *
from .stats import *
from .name import *
from .game import *
import pandas as pd

# %% ../nbs/05_match.ipynb 7
#! I think game should inherit players and teams from match
class Match:
    """
    A class to represent a game of pickleball.
    """
    def __init__(self, match_id:str):
        #Create dfs for this match
        self.match_id = match_id
        self.game_ids = game[game.match_id == self.match_id].game_id.values
        self.games = [Game(game_id) for game_id in self.game_ids]
        self.match = match[match.match_id == self.match_id]

    def __str__(self):
        return "Match({})".format(self.match_id)
    __repr__ = __str__
        
    def sumarize_match(self):
        for game in self.games:
            print(game.summarize_game())

