# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_rally.ipynb.

# %% auto 0
__all__ = ['Rally']

# %% ../nbs/07_rally.ipynb 3
from .data import *
from .stats import *
from .name import *
from .game import *
from .match import *
import pandas as pd
import matplotlib.pyplot as plt

# %% ../nbs/07_rally.ipynb 5
class Rally:
    def __init__(self, rally_id: str):
        self.rally_id= rally_id
        self.rally = rally[rally.rally_id == rally_id] # todo catch invalid rally number
        self.shots = shots[shots.rally_id == rally_id]
        self.xcoords = self.shots.sort_values("shot_nbr").loc_x
        self.ycoords = self.shots.sort_values("shot_nbr").loc_y
        # self.game_id = self.rally.game_id.iloc[0]
        # self.match_id = self.rally.match_id.iloc[0]
    
    def __str__(self):
        return f"Rally {self.rally_id}"
    __repr__ = __str__

    def plot_rally(self):
        y_arr = []
        c_map_arr = range(len(self.xcoords))
        for i, y in enumerate(self.ycoords):
            #Reverse the y location of every other shot
            if i % 2 == 0:
                y_arr.append(y)
            else:
                y_arr.append(-y) 
        plt.figure(figsize=(5,5.5))
        plt.scatter(self.xcoords, y_arr, c=c_map_arr, cmap='Blues')
        plt.axhline(y=0, color='k')

        plt.xlim(-2.5, 22.5)
        plt.ylim(-24.5, 24.5)

    # todo plot the court and rally appropriately
