# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_stats.ipynb.

# %% auto 0
__all__ = ['table_names', 'Table']

# %% ../nbs/01_stats.ipynb 3
table_names = ["tournament", "match"]

# %% ../nbs/01_stats.ipynb 5
class Table:
    "A representation of a table in the pklmart database"
    def __init__(self, 
                table_name:str # The name of the table
                ):
        if not isinstance(table_name, str):
            raise TypeError(f"table_name must be a string within {table_names}")
        if table_name not in table_names:
            raise ValueError(f"Table name {table_name} is not a name in table_names")
        self.table_name = table_name
        self._df = None
    def __str__(self): return f"{self.table_name} table"
    __repr__ = __str__


    # def pull_data(conn, tablename):

    #     """
    #     Pulls data from the database for a given table and returns a pandas dataframe.
    #     See https://pklmart.com/postgres_pklm_pklm_prd/relationships.html for a list of tables.
    #     """
    #     with conn.cursor() as cursor:
    #         try:
    #             cursor.execute(
    #                 f"SELECT column_name FROM information_schema.columns where table_name='{tablename}';"
    #             )
    #             cols = cursor.fetchall()
    #             cols = [cols[x][0] for x in range(len(cols))]
    #             cursor.execute(f"SELECT * FROM pklm_prd.{tablename}")
    #             data = cursor.fetchall()
    #             return pd.DataFrame(data, columns=cols)
    #         except Exception as inst:
    #             print(type(inst))
    #             print(inst.args)
    #             print(inst)


